### ISSUE TITLE
set readonly doesn't work as expected

### ISSUE THREAD

**Issue by onuridrisoglu** [Sergio70/Juicy-Ace-Editor#1]
readonly attribute expects boolean value rather than string.
This is the code that executes when readonly attribute is set:
`this.editor.setReadOnly( newVal === '' || newVal );`

**Comment by Sergio70** [comment]
Hi, I agree with this, but if you do a Boolean value in the setReadOnly attribute (example: false), the editor can be edited anyway:

juicyAceEditor.setReadonly (false);
->
public void setReadonly (Boolean readonly) {
getElement (). setAttribute ("readonly", readonly);
}

On the other hand, if you set a Boolean value in the setReadOnly attribute (example: false) and this value becomes a string, the editor will not allow editing.

juicyAceEditor.setReadonly (false);
->
public void setReadonly (Boolean readonly) {
getElement (). setAttribute ("readonly", String.valueOf (readonly));
}

**Comment by onuridrisoglu** [comment]
yes, that's my point exactly, in readonly mode I would expect the editor not to allow editing, and if it's set to false, it should allow editing.

However, the end result is as follows, since string "false" has a value, it is interpreted as true:
![screenshot 2018-12-14 at 13 12 57](https://user-images.githubusercontent.com/33827141/50000609-b9b17600-ffa2-11e8-9e19-39c20eaa2605.png)

**Comment by Sergio70** [comment]
You're right, 
I made the changes in the methods with Boolean values, thanks onuridrisoglu.
