### ISSUE TITLE
Component should implement HasValueAndElement to be useable with Binder

### ISSUE THREAD

**Issue by stefanuebe** [Sergio70/Juicy-Ace-Editor#2]
Currently the JAE does not implement the mentioned interface. This means that it needs to be extended to be used with a binder. 

Would be nice, if it would support that out of the box.

**Comment by Sergio70** [comment]
Thanks for this observation, if there is no problem, during the day I will do this and upload the update.

**Comment by Sergio70** [comment]
> Currently the JAE does not implement the mentioned interface. This means that it needs to be extended to be used with a binder.
> 
> Would be nice, if it would support that out of the box.

I just uploaded the new version to the vaadin directory, you can try it , if you have any other suggestions to improve it, you can feel free to comment.

**Comment by stefanuebe** [comment]
Thanks for the fast response. Looks good so far, binding is working good. 

One problem is occurring now regarding the addValueChangeListeners - since both have the same name and a functional interface as parameter, it is not possible to use simple lambdas but either listeners need to be predefined or parameters need a very long cast (see below).

I know, that this will lead to an API break, but maybe it's good to consider to remove the old addValueChangeListener method.

```
// worked only this way
 editor.addValueChangeListener((ValueChangeListener<? super ComponentValueChangeEvent<JuicyAceEditor, String>>) event -> {
        Notification.show(event.getOldValue() + " -> " + event.getValue());
});```

**Comment by Sergio70** [comment]
You're right, I had not realized this problem, I agree with you, it's best to remove the old addValueChangeListener method.

**Comment by Sergio70** [comment]
> Thanks for the fast response. Looks good so far, binding is working good.
> 
> One problem is occurring now regarding the addValueChangeListeners - since both have the same name and a functional interface as parameter, it is not possible to use simple lambdas but either listeners need to be predefined or parameters need a very long cast (see below).
> 
> I know, that this will lead to an API break, but maybe it's good to consider to remove the old addValueChangeListener method.
> 
> ```
> // worked only this way
>  editor.addValueChangeListener((ValueChangeListener<? super ComponentValueChangeEvent<JuicyAceEditor, String>>) event -> {
>         Notification.show(event.getOldValue() + " -> " + event.getValue());
> });```
> ```
The modification has already been made.
